FROM frolvlad/alpine-oraclejdk8:slim
MAINTAINER Oleg Makarov <theolegmakarov@gmail.com>

ADD airports-assembly-1.1.0.jar app.jar
RUN sh -c 'touch /app.jar'

ENTRYPOINT ["java","-jar","/app.jar"]

EXPOSE 8080
